const EXERCISES = [
	{ "title": "Prisoner Squat",          "difficulty": 2},
	{ "title": "Squat Arms OH",           "difficulty": 2},
	{ "title": "Plia Squat",              "difficulty": 2},
	{ "title": "1 Leg Squats",            "difficulty": 2},
	{ "title": "Squat Holds",             "difficulty": 1},
	{ "title": "Squat Jumps",             "difficulty": 3},
	{ "title": "Star Squat Jumps",        "difficulty": 3},
	{ "title": "Step Forward Lunges",     "difficulty": 2},
	{ "title": "Step Back Lunges",        "difficulty": 2},
	{ "title": "Side Lunges",             "difficulty": 2},
	{ "title": "Alternate Lunge Jumps",   "difficulty": 3},
	{ "title": "Skater Jumps",            "difficulty": 2},
	{ "title": "Burpees",                 "difficulty": 3},
	{ "title": "Star Burpees",            "difficulty": 3},
	{ "title": "Wide Outs",               "difficulty": 3},
	{ "title": "Lateral Hops",            "difficulty": 3},
	{ "title": "1 Leg Lateral Hops",      "difficulty": 3},
	{ "title": "Ankle Bounces",           "difficulty": 3},
	{ "title": "Calf Raises",             "difficulty": 1},
	{ "title": "Good Mornings",           "difficulty": 1},
	{ "title": "1 Leg Deadlifts",         "difficulty": 1},
	{ "title": "Plank",                   "difficulty": 2},
	{ "title": "Side Plank",              "difficulty": 2},
	{ "title": "Plank w/ leg raise",      "difficulty": 2},
	{ "title": "Super Man Plank",         "difficulty": 2},
	{ "title": "Pushups",                 "difficulty": 3},
	{ "title": "Spiderman Pushups",       "difficulty": 2},
	{ "title": "Staggered Pushups",       "difficulty": 2},
	{ "title": "T Rotation Pushups",      "difficulty": 2},
	{ "title": "Mountain Climbers",       "difficulty": 2},
	{ "title": "2 Leg Mountain Climbers", "difficulty": 2},
	{ "title": "3 pt Hop Pushup",         "difficulty": 2},
	{ "title": "Superman Hold",           "difficulty": 1},
	{ "title": "Cobra Back Raise",        "difficulty": 1},
	{ "title": "Hip Thrusts",             "difficulty": 2},
	{ "title": "1 Leg Hip Thrusts",       "difficulty": 2},
	{ "title": "Hip Bridge",              "difficulty": 1},
	{ "title": "Russian Twists",          "difficulty": 2},
	{ "title": "Bicycles",                "difficulty": 2},
	{ "title": "Toe Touch Abs",           "difficulty": 1},
	{ "title": "Suitcases",               "difficulty": 2},
	{ "title": "V leg situps",            "difficulty": 2},
	{ "title": "V ups",                   "difficulty": 2},
	{ "title": "Flutter Kicks",           "difficulty": 2},
	{ "title": "Leg Raises",              "difficulty": 2},
	{ "title": "Windshield Wipers",       "difficulty": 2},
	{ "title": "Penguins",                "difficulty": 2},
	{ "title": "Skydivers",               "difficulty": 2},
	{ "title": "Scissors",                "difficulty": 2}
]